# Generated by Django 4.2.19 on 2025-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='profile', to='Profile.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
