# Generated by Django 4.2.19 on 2025-08-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0034_alter_order_status'),
        ('Profile', '0002_alter_profile_address_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='Shop.product'),
        ),
    ]
