# Generated by Django 4.2.17 on 2025-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
