# Generated by Django 4.2.17 on 2025-01-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0006_product_image_alter_cart_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="name",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Shop.product",
            ),
        ),
    ]
