# Generated by Django 4.2.17 on 2025-02-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='token',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
