# Generated by Django 4.2.17 on 2025-02-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_alter_order_token_alter_product_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
    ]
