# Generated by Django 4.2.17 on 2025-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_remove_product_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
