# Generated by Django 4.2.17 on 2025-02-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_alter_order_token_alter_product_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, default='O-6594933', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='token',
            field=models.CharField(blank=True, default='P-3176310', max_length=10, null=True),
        ),
    ]
