# Generated by Django 4.2.17 on 2025-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_alter_order_token_alter_product_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('OnTheway', 'Ontheway'), ('Canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
