# Generated by Django 4.2.19 on 2025-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0024_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/no_image.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('OnTheWay', 'OnThWway'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
