# Generated by Django 4.2.19 on 2025-08-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0027_alter_category_icon_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='images/no_image.png', upload_to='images/categories'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/products'),
        ),
    ]
