# Generated by Django 4.2.19 on 2025-08-01 09:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0028_alter_category_icon_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/no_image.png', force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 800], upload_to='images/categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/no_image.png', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='images/products'),
        ),
    ]
