# Generated by Django 4.2.19 on 2025-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0030_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('درحال پردازش', 'درحال پردازش'), ('تایید شده', 'تایید شده'), ('در حال ارسال', 'در حال ارسال'), ('لغو شده', 'لغو شده'), ('سفارش کامل شده', 'سفارش کامل شده')], default='درحال پردازش', max_length=30),
        ),
    ]
