# Generated by Django 4.2.19 on 2025-08-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0031_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('درحال پردازش', 'pending'), ('تایید شده', 'confirmed'), ('در حال ارسال', 'ontheway'), ('لغو شده', 'canceled'), ('سفارش کامل شده', 'completed')], default='درحال پردازش', max_length=30),
        ),
    ]
