# Generated by Django 4.2.19 on 2025-08-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'درحال پردازش'), ('confirmed', 'تایید شده'), ('ontheway', 'در حال ارسال'), ('cancelled', 'لغو شده'), ('completed', 'سفارش کامل شده')], default='pending', max_length=30),
        ),
    ]
