# Generated by Django 4.2.19 on 2025-08-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0035_product_rating_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='review',
            new_name='comment',
        ),
    ]
