# Generated by Django 4.2.19 on 2025-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0036_rename_review_productreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.BigIntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
