# Generated by Django 4.2.19 on 2025-09-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0037_alter_cart_total_price_alter_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(blank=True, choices=[('express', 'ارسال فوری'), ('standard', 'ارسال عادی'), ('pickup', 'تحویل حضوری')], max_length=11, null=True),
        ),
    ]
